# Generated by Django 4.2.1 on 2023-05-18 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_food_image_alter_food_calories_alter_food_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carbs_all', models.DecimalField(decimal_places=2, max_digits=5)),
                ('protein_all', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fats_all', models.DecimalField(decimal_places=2, max_digits=5)),
                ('calories_all', models.PositiveIntegerField()),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('food_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.food')),
            ],
        ),
    ]
