# Generated by Django 4.2.1 on 2023-05-18 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_stats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stats',
            old_name='calories_all',
            new_name='calories_full',
        ),
        migrations.RenameField(
            model_name='stats',
            old_name='carbs_all',
            new_name='carbs_full',
        ),
        migrations.RenameField(
            model_name='stats',
            old_name='fats_all',
            new_name='fats_full',
        ),
        migrations.RenameField(
            model_name='stats',
            old_name='protein_all',
            new_name='protein_full',
        ),
    ]
